apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: osjx86np4-go
  janus-idp.io/tekton: osjx86np4-go
  backstage.io/kubernetes-id: osjx86np4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: osjx86np4-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
